### ISSUE TITLE
ItemConditionEvent not returning Player

### ISSUE THREAD

**Issue by Mythikos** [Notulp/Pluton#148]
In the documentation for ItemConditionEvent, it says it is suppose to return a player however it only returns Item and Amount. The hook is pretty much useless without returning Player. 

http://forum.pluton-team.org/wiki/itemconditionevent/
https://github.com/Notulp/Pluton/blob/master/Pluton/Events/ItemConditionEvent.cs

**Comment by balu92** [comment]
fixed: https://github.com/Notulp/Pluton/commit/169ee8b99f0e55b988fd007e4e4192c4e3ce7e17
