### ISSUE TITLE
HurtEvent issue with returning Weapon

### ISSUE THREAD

**Issue by Mythikos** [Notulp/Pluton#149]
It appears that the HurtEvent as used with hook On_CorpseHurt does not return the weapon in the instance of a melee weapon.

Rifles/Bows return a valid weapon entity
Hatchets/Pickaxes/Other Melee weapons return null/nil

My Code:
```lua
function On_CorpseHurt(HurtEvent)
    local ply = HurtEvent.Attacker
    local weapon = HurtEvent.Weapon
    if weapon == nil then
    	weapon = {}
    	weapon.Name = "unknown weapon"
    end
    local dType = HurtEvent.DamageType

    if ply.IsPlayer() then
        Server.Broadcast(ply.Name.." hit a corpse using a(n) "..weapon.Name.." (Damage Type: "..tostring(dType)..")!")
    end
end
```

The output:
http://www.mythicservers.com/images/mythic/2015-11-05_19-00-10.png

1st was bolt action
2nd was stone hatchet
3rd was stone pickaxe

**Comment by balu92** [comment]
fixed: https://github.com/Notulp/Pluton/commit/980758f9b702216c73b0e25a027b9ed799129e31
