### ISSUE TITLE
 BasePlayer:Die (HitInfo): IL_0026: c

### ISSUE THREAD

**Issue by BloodyMikey** [Notulp/Pluton#158]
NullReferenceException: Object reference not set to an instance of an object
213.65.132.103:59624/76561198042925127/Bloody Mikey kicked: RPC Error: onproject
ileattack
InvalidProgramException: Invalid IL code in BasePlayer:Die (HitInfo): IL_0026: c
all      0x0a000718

**Comment by balu92** [comment]
Sry for being late on this, now it's fixed.
