### ISSUE TITLE
new locations of calls and hooks breaks pluton

### ISSUE THREAD

**Issue by stopspazzing** [Notulp/Pluton#38]
Submitted by: XCorrosionX
From channel: #pluton
At 2015-01-31 02:05:36 UTC

**Comment by stopspazzing** [comment]
17:43 PhantomNZ: In World.cs, change all GameManager.CreateEntity calls to GameManager.server.CreateEntity
17:43 PhantomNZ: In player.cs and buildingpart.cs, networkData.WriteUInt becomes networkData.WriteUInt32
17:44 PhantomNZ: 1 error left and that's in server.cs .. return consolesystem.run(command, wantsreply)
17:45 PhantomNZ: they've made run a class now and it has a static method called unrestricted that does the same thing

**Comment by balu92** [comment]
Oh yeah, fixed and thanks.
