### ISSUE TITLE
Entity.Location

### ISSUE THREAD

**Issue by jakkee** [Notulp/Pluton#46]
Entity.Location returns 0.0, 0.0, 0.0.
No errors in logs or logs.
Code I was using: (Python)
    def On_Placement(self, BuildingEvent):
        if BuildingEvent.Builder.Admin:
            BuildingEvent.Builder.Message(str(BuildingEvent.BuildingPart.Location))

**Comment by balu92** [comment]
Fixed, thanks!
https://github.com/Notulp/Pluton/commit/4e6880dea6dae0869990c329d801413ffba8698b
